
language: node_js
node_js:
  - 8
  - 9
  - 10
  - 11
  - 12
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn lint
#- yarn test --coverage && yarn coveralls < ./coverage/lcov.info
- yarn build
